- zappy_gui_src/main.cpp
This PR fixes the main thread in the GUI binary not used. It use the main thread to do graphical work instead of the new thread
Closed Issues : #98
> 🐛 Fix the main thread not used

- docs/docs/zappy/GUI_PROTOCOL.md
- zappy_gui_src/Graphic/Window/WindowEvent.cpp
This PR adds the documentation for the protocol GUI
This PR fix the camera movement
Closed Issues : #40 #112
> :bug: :memo:  fix camera movement & documentation GUI

- zappy_server_src/client.c
- zappy_server_src/exec_command.c
- zappy_server_src/execution_command/check_ticks.c
- zappy_server_src/execution_command/forward_command.c
- zappy_server_src/execution_command/get_command_handler.c
- zappy_server_src/execution_command/look_command.c
- zappy_server_src/include/command_handler.h
- zappy_server_src/parser.c
This PR adds the handling of the look command to see tiles in front of the player
Closed Issues : #123
> :sparkles: handle look command

- zappy_ai_src/Data/Data.hpp
- zappy_ai_src/Interface/Interface.cpp
- zappy_ai_src/Interface/Interface.hpp
- zappy_ai_src/Interface/Inventory.cpp
- zappy_ai_src/main.cpp
This PR add the handling of the output given by the server when sending the INVENTORY command
Closed Issues : #10
> Add inventory command to the ai

- zappy_server_src/execution_command/command_association_list.c
- zappy_server_src/execution_command/set_command.c
- zappy_server_src/execution_command/take_command.c
- zappy_server_src/include/command.h
- zappy_server_src/include/command_handler.h
This PR add the handling of the set command from the AI to the server
> ✨ Set command handling for the server

- zappy_server_src/execution_command/check_ticks.c
- zappy_server_src/include/zappy.h
- zappy_server_src/map.c
- zappy_server_src/map_creation.c
- zappy_server_src/map_update.c
- zappy_server_src/zappy.c
This PR add the refresh of the map resources every 20 ticks
Closed Issues : #129
> ✨ Implement tick count and map update logic

- docs/docs/zappy/AI_PROTOCOL.md
This PR adds the AI protocol to the documentation
Closed Issues : #186
> :sparkles: Add AI Protocol documentation for client/server communication

- Makefile
- tests/zappy_serv.sh
- zappy_server_src/command.c
- zappy_server_src/zappy.c
This PR fix server clossing for no reason (when a player disconnect he was not removing it from the list)
This PR also add a message when the server is starting whith data showing 
Closed Issues : #182
> :bug: Fix server closing for no reason & add hello message 

- zappy_ai_src/ForkWrapper/Fork.cpp
- zappy_ai_src/ForkWrapper/Fork.hpp
- zappy_ai_src/Interface/Communication.cpp
- zappy_ai_src/Interface/Interaction.cpp
- zappy_ai_src/Interface/Interface.cpp
- zappy_ai_src/Interface/Interface.hpp
- zappy_ai_src/Interface/Inventory.cpp
- zappy_ai_src/Interface/Mouvement.cpp
- zappy_ai_src/Interface/Special.cpp
This PR adds documentation and basics tools for the AI
Closed Issues : #188
> ✨ Add doxygen documentation of the interface of the ai

- zappy_server_src/execution_command/player/set_command.c
- zappy_server_src/execution_command/player/take_command.c
This PR fix two bug with set and take:
1- if set or take did not have argument the server would segfault
2- Set and Take now send pin command to the GUI
> :bug: fix bugs with take and set

- tests/zappy_gui.sh
- tests/zappy_serv.sh
- zappy_gui_plugins_src/frequencyPlugin.cpp
- zappy_gui_src/Connection/Commands/CommandServer.cpp
- zappy_gui_src/DataManager/Egg.hpp
- zappy_gui_src/DataManager/GameDataManager.cpp
- zappy_gui_src/DataManager/GameDataManager.hpp
- zappy_gui_src/DataManager/GameTile.cpp
- zappy_gui_src/DataManager/GameTile.hpp
- zappy_gui_src/DataManager/Player.cpp
- zappy_gui_src/DataManager/Player.hpp
- zappy_gui_src/DataManager/PlayerGetSeter.cpp
- zappy_gui_src/Graphic/Window/window.cpp
- zappy_gui_src/Graphic/Window/window.hpp
- zappy_gui_src/Graphic/graphic.cpp
- zappy_gui_src/main.cpp
- zappy_server_src/command.c
- zappy_server_src/command_parsing/push_command_to_queue.c
This PR fix the different problems like error when mutiple players connecting
- invisible players
- mesh error creation & initialisation
- ...
> :bug: fix the refactor problems of the gui

- libc/logs.c
- zappy_server_src/delete_egg.c
- zappy_server_src/execution_command/player/eject_command.c
- zappy_server_src/include/client.h
- zappy_server_src/include/zappy.h
- zappy_server_src/zappy.c
Now sends the correct eject: Direction to all concerned players and destroys eggs (ToT)
Closed Issues : #198
> 🐛 fix eject command

- zappy_server_src/parser.c
This PR fixes the server that would start even with a value to high for the frequency.
> 🐛 Server can no longuer start with a frequency > 200

- zappy_ai_src/modules/KirbyModule.cpp
- zappy_ai_src/modules/KirbyModule.hpp
This PR adds the kirby module use to handle the Kirby automaton
Closed Issues : #237
> ✨ Add kirby module

- zappy_gui_plugins_src/globalDataPlugin.cpp
- zappy_gui_src/Graphic/Window/WindowEvent.cpp
- zappy_gui_src/Graphic/Window/window.hpp
This PR adds a movement for going up or down to the camera
- By pressing space or left control
> :sparkles: Up down camera

- zappy_gui_plugins_src/graphRessourcesPlugin.cpp
- zappy_gui_plugins_src/graphRessourcesPlugin.hpp
- zappy_server_src/parser.c
This PR fix the limits of map size and frequency
and fix the graph limits plugin to always be visible even with high numbers
Closed Issues : #234
> :bug: unlock map size

- README.md
This PR adds README with installation instructions for irrlicht on UBUNTU BECAUSE WHY !!!
> 📝 Update README with installation instructions for irrlicht

- zappy_server_src/execution_command/command_association_list.c
- zappy_server_src/execution_command/player/broadcast_command.c
- zappy_server_src/execution_command/player/connect_nbr_command.c
- zappy_server_src/execution_command/player/eject_command.c
- zappy_server_src/execution_command/player/fork_command.c
- zappy_server_src/execution_command/player/forward_command.c
- zappy_server_src/execution_command/player/incantation_command.c
- zappy_server_src/execution_command/player/inventory_command.c
- zappy_server_src/execution_command/player/left_command.c
- zappy_server_src/execution_command/player/look_command.c
- zappy_server_src/execution_command/player/right_command.c
- zappy_server_src/execution_command/player/set_command.c
- zappy_server_src/execution_command/player/take_command.c
- zappy_server_src/include/command_handler.h
This PR add the inventory command. It is sent by the AIs to the server and the server respond by sending their inventory, like this for example: [food 8, linemate 1, deraumere 0, sibur 0, mendiane 0, phiras 0, thystame 0].
> ✨ Add inventory command

- zappy_gui_src/Connection/Commands/CommandServer.cpp
- zappy_gui_src/Connection/ServerGUI.cpp
- zappy_gui_src/Connection/ServerGUI.hpp
- zappy_gui_src/Connection/connectionWithServer.cpp
- zappy_gui_src/Graphic/Window/window.cpp
- zappy_gui_src/Graphic/Window/window.hpp
- zappy_gui_src/Graphic/graphic.cpp
This PR fix the network part where irrlicht command where called
> :sparkles: remove the irrlicht call command in the network part

- zappy_server_src/execution_command/player/look_command.c
This PR fix the formating of look command
Closed Issues : #264
> :bug: Refactor buffer initialization and formatting in look_command

- tests/zappy_serv.sh
- zappy_server_src/zappy.c
This PR modifie the zappy.c file to make the server stop responding and receiving messages after a team has won.
> ♻️ Server now stop sending and receving message after a team has won

- zappy_server_src/include/zappy.h
- zappy_server_src/main.c
- zappy_server_src/zappy.c
This PR Fix the coding style error of the struct as static for a boolean to handle the server shtudown
Closed Issues : #286
> ♻️ Refactor static struct to boolean for server shutdown handling

- zappy_gui_plugins_src/ConnectionStatePlugin_Water.hpp
- zappy_gui_plugins_src/TileDataPluginDebug.cpp
- zappy_gui_plugins_src/TileDataPluginDebug.hpp
- zappy_server_src/command.c
- zappy_server_src/command_parsing/commands_name_size_lists.c
- zappy_server_src/command_parsing/extract_command.c
- zappy_server_src/execution_command/command_association_list.c
- zappy_server_src/execution_command/gui/d_ressource_command.c
- zappy_server_src/include/command_handler.h
This PR adds a debug tile plugin to add or remove items from a tile
> :saprkles: add Debug tile plugin

- zappy_server_src/client.c
- zappy_server_src/zappy.c
This PR fix the hard coded write at the check of new clients connection and verify the return value of the close fd
Closed Issues : #284
> 🐛 Remove the hard coded write and check for close return value

- zappy_gui_src/DataManager/DataManager.cpp
- zappy_gui_src/DataManager/DataManager.hpp
- zappy_gui_src/Graphic/Window/window.cpp
- zappy_gui_src/main.cpp
This PR adds a -o for optimize version
Closed Issues :
> ✨ Add optimization state management to DataManager and update window creation logic

- zappy_ai_src/Data/Data.hpp
- zappy_ai_src/Interface/Interaction.cpp
- zappy_ai_src/Interface/Interface.cpp
- zappy_ai_src/Interface/Interface.hpp
This PR adds the handling of the eject command coming from the server
Closed Issues : #299
> ✨ Add EJECT handling

- docs/docusaurus.config.ts
- docs/src/pages/index.tsx
Remove weird text in the docusaurus homepage :p
> 📝 Remove ZIP ZOUP from docusaurus homepage

- docs/docs/zappy/GUI_PROTOCOL.md
- docs/docs/zappy/GUI_RFC.txt
- zappy_gui_src/Connection/Commands/CommandServer.cpp
- zappy_gui_src/DataManager/Player.hpp
- zappy_gui_src/tools/MeshImporter.cpp
This PR adds last part of missing protocol
> :memo: Doc protocol scale up
